name: Build project and run tests for PR's

on:
  pull_request:
    branches:
    - main
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and test app
        run: mvn clean install
